### Домашнее задание "Продвинутая линейная алгебра".
#### Уровень 0:
Придумайте матрицы, которые обладают следующими свойствами:

a) Диагональная, ортогональная, но не единичная(!)

b) Верхнетреугольная, ортогональная

c) Нижнетреугольная, ортогональная

d) Матрица, у которой определитель = 1, и все элементы не равны 0

P.S. Во всех пунктах ответом должна быть ненулевая матрица размерности не менее 2!

Найдите собственные значения и собственные вектора матриц:

m = np.array([[2, 2],
              [1, 3]])
print(m)


In [7]:
import numpy as np
import pylab as pl
import warnings

from matplotlib import pyplot as plt
from scipy import linalg
from sklearn.datasets import load_digits
from sklearn.decomposition import TruncatedSVD
from sklearn.ensemble import RandomForestClassifier
warnings.filterwarnings("ignore")

In [8]:
from scipy.stats import ortho_group

In [ ]:
# Диагональная, ортогональная, но не единичная(!)

In [9]:
mat_ort = ortho_group.rvs(dim=3)
mat_ort

array([[-0.65195542, -0.70844986, -0.27028305],
       [ 0.41584492, -0.03599398, -0.90872297],
       [ 0.6340561 , -0.7048427 ,  0.31807174]])

In [11]:
mat_ort @ mat_ort.T

array([[ 1.00000000e+00, -3.14881977e-18,  1.71127237e-16],
       [-3.14881977e-18,  1.00000000e+00,  5.06401140e-16],
       [ 1.71127237e-16,  5.06401140e-16,  1.00000000e+00]])

In [12]:
# Верхнетреугольная, ортогональная

up = np.triu(mat_ort, 0)
# up = np.triu(mat_ort, +1)
print(up)

[[-0.65195542 -0.70844986 -0.27028305]
 [ 0.         -0.03599398 -0.90872297]
 [ 0.          0.          0.31807174]]


In [14]:
# Нижнетреугольная, ортогональная

lo = np.tril(mat_ort, 0)
# lo = np.tril(mat_ort, -1)
print(lo)

[[-0.65195542  0.          0.        ]
 [ 0.41584492 -0.03599398  0.        ]
 [ 0.6340561  -0.7048427   0.31807174]]


In [19]:
# Матрица, у которой определитель = 1, и все элементы не равны 0

det = np.linalg.det(mat_ort)
print(mat_ort)
print(round(det))

[[-0.65195542 -0.70844986 -0.27028305]
 [ 0.41584492 -0.03599398 -0.90872297]
 [ 0.6340561  -0.7048427   0.31807174]]
1.0


In [16]:
m2 = np.array([[2, 3, 6], [1, 1, 4], [1, 2, 1]], dtype=np.float32)
det = np.linalg.det(m2)
print(m2)
print(det)

[[2. 3. 6.]
 [1. 1. 4.]
 [1. 2. 1.]]
1.0


In [20]:
# Найдите собственные значения и собственные вектора матриц:

a = np.array([[2, 2],
              [1, 3]])
w, v = np.linalg.eig(a)
print(a)

[[2 2]
 [1 3]]


In [21]:
for i in range(len(w)):
    print("Собственное значение " + str(w[i]))
    print("соответствующий ему собственный вектор " + str(v[:,i]))

Собственное значение 1.0
соответствующий ему собственный вектор [-0.89442719  0.4472136 ]
Собственное значение 4.0
соответствующий ему собственный вектор [-0.70710678 -0.70710678]


In [22]:
# Найдите спектральное разложение матрицы:


l = np.array([[1, 2],
              [2,3]])
print(l)

[[1 2]
 [2 3]]


In [23]:
a, U = linalg.eig(l)
print('Собственные значения:')
print(np.array(a, dtype=float))
print('\nСобственные значения:')
print(U)

Собственные значения:
[-0.23606798  4.23606798]

Собственные значения:
[[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


In [24]:
print(np.array(U.dot(np.diag(a)).dot(U.T), dtype=float))

[[1. 2.]
 [2. 3.]]
